apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-and-mongodb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-and-mongodb
  template:
    metadata:
      labels:
        app: app-and-mongodb
    spec:
      containers:
      - name: nodejs-app
        image: marrapu07578/myapp:latest
        ports:
        - containerPort: 3028
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/logistics"
        - name: PORT
          value: "3039"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "logistics"