version: '3.8'
services:
  logistics-app:
    build: .
    ports:
      - '3039:3039'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/logistics
    volumes:
      - .:/usr/src/app  
    working_dir: /usr/src/app
    command: npm start  

  mongodb:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - ./data:/data/db  
